export const cardPacks = [
	{
		id: 1,
		product: "Classic Monsters",
		image1: require("../../../../public/yugioh/normal/blue-eyes.jpg"),
		image2: require("../../../../public/yugioh/normal/red-eyes.jpg"),
		image3: require("../../../../public/yugioh/normal/darkmagician.jpg"),
		image4: require("../../../../public/yugioh/normal/gaia.jpg"),
		image5: require("../../../../public/yugioh/normal/skull.jpg"),
		price: 9.99,
		desc: "These classic monsters can be a wonderful addition to your Yu-Gi-Oh! collection. This pack features cards from the original version of this legendary card game like Dark Magician, Summoned Skull, and of course the legendary Blue-Eyes White Dragon.",
	},
	{
		id: 2,
		product: "Classic Spells and Traps",
		image1: require("../../../../public/yugioh/spellsandtraps/polymerization.jpg"),
		image2: require("../../../../public/yugioh/spellsandtraps/greed.jpg"),
		image3: require("../../../../public/yugioh/spellsandtraps/cylinder.jpg"),
		image4: require("../../../../public/yugioh/spellsandtraps/haunted.jpg"),
		image5: require("../../../../public/yugioh/spellsandtraps/mst.jpg"),
		price: 6.99,
		desc: "Some of the simplest and most powerful spells and traps can be found in these packs. Shut down your opponent's spells and traps with Mystical Space Typhoon, give them a taste of their own medicine with Magic Cylinder, or bring back your main monster with Call of the Haunted.",
	},
	{
		id: 3,
		product: "Classic Effect Monsters",
		image1: require("../../../../public/yugioh/effect/jinzo.jpg"),
		image2: require("../../../../public/yugioh/effect/darkmagiciangirl.jpg"),
		image3: require("../../../../public/yugioh/effect/wizard.jpg"),
		image4: require("../../../../public/yugioh/effect/man-eater.jpg"),
		image5: require("../../../../public/yugioh/effect/buster.jpg"),
		price: 7.99,
		desc: "Nothing beats these staple Yu-Gi-Oh! monsters. Complete your deck of dark fiend types with the mysterious Jinzo, counter dragon type decks with the warrior Buster Blader, bolster your spellcaster deck with Dark Magician Girl, or add some flip effects to your deck with the likes of Man-Eater Bug.",
	},
	{
		id: 4,
		product: "Tuner Monsters",
		image1: require("../../../../public/yugioh/tuners/junk.jpg"),
		image2: require("../../../../public/yugioh/tuners/jet.jpg"),
		image3: require("../../../../public/yugioh/tuners/galaxy.jpg"),
		image4: require("../../../../public/yugioh/tuners/torque.jpg"),
		image5: require("../../../../public/yugioh/tuners/chameleon.jpg"),
		price: 4.99,
		desc: "Synchros are part of the newer generation of Yu-Gi-Oh! and were introduced in the Yu-Gi-Oh! 5D's series. To summon Synchro Monsters, Tuner Monsters are required to complete the Synchro Summon, which is essentially a special tribute that requires a specific kind of monster. This pack contains some of these monsters.",
	},
	{
		id: 5,
		product: "Synchro Monsters",
		image1: require("../../../../public/yugioh/synchro/stardust.jpg"),
		image2: require("../../../../public/yugioh/synchro/jetwarrior.jpg"),
		image3: require("../../../../public/yugioh/synchro/junkwarrior.jpg"),
		image4: require("../../../../public/yugioh/synchro/blackrose.jpg"),
		image5: require("../../../../public/yugioh/synchro/gaiaforce.jpg"),
		price: 8.99,
		desc: "Synchro Monsters are powerful effect monsters that must be summoned with the Synchro Summon, a unique kind of special summon that requires at least one Tuner Monster. This pack features noteworthy Synchros like Stardust Dragon, Junk Warrior, and Black Rose Dragon. ",
	},
	{
		id: 6,
		product: "Xyz Monsters",
		image1: require("../../../../public/yugioh/xyz/utopia.jpg"),
		image2: require("../../../../public/yugioh/xyz/flaremetal.jpg"),
		image3: require("../../../../public/yugioh/xyz/gachi.jpg"),
		image4: require("../../../../public/yugioh/xyz/grenosaurus.jpg"),
		image5: require("../../../../public/yugioh/xyz/leviathan.jpg"),
		price: 7.99,
		desc: "Xyz Monsters are a newer kind of monster introduced in Yu-Gi-Oh! ZEXAL. They are summoned through the Xyz summon, which is a special summon that requires you to offer up a number of monsters of the same level. Powerful effects can be activated by removing the monsters as materials.",
	},
	{
		id: 7,
		product: "Pendulum Monsters",
		image1: require("../../../../public/yugioh/pendulum/jackal.jpg"),
		image2: require("../../../../public/yugioh/pendulum/hamster.jpg"),
		image3: require("../../../../public/yugioh/pendulum/oddeyes.jpg"),
		image4: require("../../../../public/yugioh/pendulum/stargazer.jpg"),
		image5: require("../../../../public/yugioh/pendulum/timegazer.jpg"),
		price: 12.99,
		desc: "Pendulum Monsters are a monster type introduced in Yu-Gi-Oh! ARC-V. They can create a Pendulum Scale in the Spell/Trap Zone, which then turns it into a Pendulum Zone that allows the user to special summon Pendulums. They can also be summoned like regular monsters, which grants them great versatility in duels.",
	},
	{
		id: 8,
		product: "Fusion Monsters",
		image1: require("../../../../public/yugioh/fusions/ultimate.jpg"),
		image2: require("../../../../public/yugioh/fusions/champion.jpg"),
		image3: require("../../../../public/yugioh/fusions/dragoon.jpg"),
		image4: require("../../../../public/yugioh/fusions/thousand.jpg"),
		image5: require("../../../../public/yugioh/fusions/fivehead.jpg"),
		price: 9.99,
		desc: "Fusion Monsters are strong monsters that have high damage and defense and are created using multiple monsters of the same type or with specific monsters. They are special summoned through the Fusion Summon by using a fusion spell, most commonly with Polymerization.",
	},
	{
		id: 9,
		product: "Pokemon Gen 1 Booster Pack",
		image1: require("../../../../public/pokemon/gen1/blastoise.jpg"),
		image2: require("../../../../public/pokemon/gen1/gyarados.jpg"),
		image3: require("../../../../public/pokemon/gen1/machamp.jpg"),
		image4: require("../../../../public/pokemon/gen1/golduck.jpg"),
		image5: require("../../../../public/pokemon/gen1/charizard.jpg"),
		price: 14.99,
		desc: "Collect cards from the start of this legendary franchise. All cards from the classic lineup of 151 Pokemon can be found in these booster packs, ranging from the fan favorites like Blastoise and Charizard to more niche picks like Golduck.",
	},
	{
		id: 10,
		product: "Pokemon Gen 2 Booster Pack",
		image1: require("../../../../public/pokemon/gen2/feraligatr.jpg"),
		image2: require("../../../../public/pokemon/gen2/typhlosion.jpg"),
		image3: require("../../../../public/pokemon/gen2/ursaring.jpg"),
		image4: require("../../../../public/pokemon/gen2/tyranitar.jpg"),
		image5: require("../../../../public/pokemon/gen2/houndoom.jpg"),
		price: 15.99,
		desc: "The second generation of Pokemon is about as beloved as the first. You can find just about any cards of Gen 2 here, such as the starters and their various evolutions and other cool Pokemon like Houndoom and Tyranitar. ",
	},
	{
		id: 11,
		product: "Pokemon Gen 3 Booster Pack",
		image1: require("../../../../public/pokemon/gen3/mightyena.jpg"),
		image2: require("../../../../public/pokemon/gen3/aggron.jpg"),
		image3: require("../../../../public/pokemon/gen3/blaziken.jpg"),
		image4: require("../../../../public/pokemon/gen3/metagross.jpg"),
		image5: require("../../../../public/pokemon/gen3/shiftry.jpg"),
		price: 16.99,
		desc: "Gen 3 saw some more interesting designs and concepts amongst its Pokemon. The iconic Blaziken, the final evolution of the starter Torchic, can be found here. Metagross, Aggron, and Shiftry showcase some of the more unique designs that Gen 3 introduced.",
	},
	{
		id: 12,
		product: "Pokemon Gen 4 Booster Pack",
		image1: require("../../../../public/pokemon/gen4/dusknoir.jpg"),
		image2: require("../../../../public/pokemon/gen4/empoleon.jpg"),
		image3: require("../../../../public/pokemon/gen4/garchomp.jpg"),
		image4: require("../../../../public/pokemon/gen4/infernape.jpg"),
		image5: require("../../../../public/pokemon/gen4/torterra.jpg"),
		price: 18.99,
		desc: "Gen 4 introduced more iconic Pokemon that are still fan favorites to this day. The starters Piplup, Turtwig, and Chimchar all have great evolutions. Garchomp demonstrates great destructive power. Dusknoir utilizes vast psychic abilites to defeat its enemies.",
	},
	{
		id: 13,
		product: "Pokemon Gen 5 Booster Pack",
		image1: require("../../../../public/pokemon/gen5/oshawott.jpg"),
		image2: require("../../../../public/pokemon/gen5/sawk.jpg"),
		image3: require("../../../../public/pokemon/gen5/seismitoad.jpg"),
		image4: require("../../../../public/pokemon/gen5/snivy.jpg"),
		image5: require("../../../../public/pokemon/gen5/tepig.jpg"),
		price: 24.99,
		desc: "Gen 5 of Pokemon has simple and memorable designs. Snivy, Oshawott, and Tepig are the starters for this generation and they all have a cute apperance to them. The fighting champion Sawk and the great Seismitoad are examples of unique Gen 5 Pokemon.",
	},
	{
		id: 14,
		product: "Pokemon Gen 6 Booster Pack",
		image1: require("../../../../public/pokemon/gen6/aegislash.jpg"),
		image2: require("../../../../public/pokemon/gen6/greninja.jpg"),
		image3: require("../../../../public/pokemon/gen6/pangoro.jpg"),
		image4: require("../../../../public/pokemon/gen6/talonflame.jpg"),
		image5: require("../../../../public/pokemon/gen6/trevenant.jpg"),
		price: 24.99,
		desc: "This pack contains a variety of Pokemon from Gen 6. This generation includes plenty of interesting designs, such as Stage 2 starter evolutions Talonflame and Greninja. This generation also introduced designs based on various weapons such as the sword pokemon, Aegislash.",
	},
	{
		id: 15,
		product: "Pokemon Gen 7 Booster Pack",
		image1: require("../../../../public/pokemon/gen7/crabominable.jpg"),
		image2: require("../../../../public/pokemon/gen7/decidueye.jpg"),
		image3: require("../../../../public/pokemon/gen7/golisopod.jpg"),
		image4: require("../../../../public/pokemon/gen7/incineroar.jpg"),
		image5: require("../../../../public/pokemon/gen7/salazzle.jpg"),
		price: 24.99,
		desc: "Pokemon continues to demonstrate its creative art and concepts with cards from the seventh generation. The fire/fighting type Incineroar has become a fan favorite with its wrestling moves and attitude. Decidueye presents a fresh take on the grass/flying hybrid type.",
	},
	{
		id: 16,
		product: "Pokemon Gen 8 Booster Pack",
		image1: require("../../../../public/pokemon/gen8/corviknight.jpg"),
		image2: require("../../../../public/pokemon/gen8/dragapult.jpg"),
		image3: require("../../../../public/pokemon/gen8/grimmsnarl.jpg"),
		image4: require("../../../../public/pokemon/gen8/rillaboom.jpg"),
		image5: require("../../../../public/pokemon/gen8/toxtricity.jpg"),
		price: 24.99,
		desc: "Gen 8 is one of the most recent iterations of Pokemon. Of course, it continues the theme of fire, grass, and water type starters, with Rillaboom being the Stage 2 grass type evolution. The Stage 2 evolution Toxtricity is a cool design that resembles a rockstar.",
	},
	{
		id: 17,
		product: "Magic The Gathering Creatures",
		image1: require("../../../../public/magic/creatures/aegis.jpg"),
		image2: require("../../../../public/magic/creatures/beanstalk.jpg"),
		image3: require("../../../../public/magic/creatures/ghalta.jpg"),
		image4: require("../../../../public/magic/creatures/hundred.jpg"),
		image5: require("../../../../public/magic/creatures/jermane.jpg"),
		price: 13.99,
		desc: "Every Magic The Gathering deck requires some creatures to complete its structure. This pack offers creatures like the Aegis Turtle, the Beanstalk Giant, and the Hundred-Handed One. Each pack also has a chance to contain a legendary creature like Jermane, Pride of the Circus.",
	},
	{
		id: 18,
		product: "Magic The Gathering Enchantments",
		image1: require("../../../../public/magic/enchantments/berserker.jpg"),
		image2: require("../../../../public/magic/enchantments/dream.jpg"),
		image3: require("../../../../public/magic/enchantments/hyena.jpg"),
		image4: require("../../../../public/magic/enchantments/sentinel.jpg"),
		image5: require("../../../../public/magic/enchantments/spirit.jpg"),
		price: 14.99,
		desc: "Enchantments are designed to strengthen other cards in Magic The Gathering, particularly creatures. This pack will provide enchantments for all colors and archetypes. Creature enchants and permanent enchants alike are featured, such as Sentinel's Eyes and Dream Leash.",
	},
	{
		id: 19,
		product: "Magic The Gathering Sorceries",
		image1: require("../../../../public/magic/sorceries/blood.jpg"),
		image2: require("../../../../public/magic/sorceries/broken.jpg"),
		image3: require("../../../../public/magic/sorceries/rise.jpg"),
		image4: require("../../../../public/magic/sorceries/titanic.jpg"),
		image5: require("../../../../public/magic/sorceries/tooth.jpg"),
		price: 18.99,
		desc: "Sorceries in Magic The Gathering are spells that can be used to help users navigate their decks, get more creatures out, or destroy opponent cards. Their ablities are typically more powerful than instants. Effects like Blood Tribute or Titanic Ultimatum can be powerful additions to the deck.",
	},
	{
		id: 20,
		product: "Magic The Gathering Instants",
		image1: require("../../../../public/magic/instants/anticipate.jpg"),
		image2: require("../../../../public/magic/instants/berserk.jpg"),
		image3: require("../../../../public/magic/instants/entomb.jpg"),
		image4: require("../../../../public/magic/instants/harvest.jpg"),
		image5: require("../../../../public/magic/instants/shock.jpg"),
		price: 15.99,
		desc: "Instants are cards that provide quick and simple effects in Magic The Gathering. From doing immediate damage to searching the deck for a certain type of card, players need instants to provide some quick firepower to their decks and gain the upper edge.",
	},
	{
		id: 21,
		product: "Magic The Gathering Artifacts",
		image1: require("../../../../public/magic/artifacts/cauldron.jpg"),
		image2: require("../../../../public/magic/artifacts/lantern.jpg"),
		image3: require("../../../../public/magic/artifacts/mirror.jpg"),
		image4: require("../../../../public/magic/artifacts/mycosynth.jpg"),
		image5: require("../../../../public/magic/artifacts/vault.jpg"),
		price: 20.99,
		desc: "Artifacts provide lasting effects that will remain on the field until the artifact is destroyed. They are powerful utilities that are designed to work with certain archetypes and are necessary components of the deck. Artifacts like Chromatic Lantern can empower lands, while Cauldron of Eternity can manipulate creatures. ",
	},
	{
		id: 22,
		product: "Magic The Gathering Lands",
		image1: require("../../../../public/magic/lands/forest.jpg"),
		image2: require("../../../../public/magic/lands/island.jpg"),
		image3: require("../../../../public/magic/lands/mountain.jpg"),
		image4: require("../../../../public/magic/lands/plains.jpg"),
		image5: require("../../../../public/magic/lands/swamp.jpg"),
		price: 12.99,
		desc: "Lands provide the basis that creatures can stand on. They are permanent and necessary to create deck synergy between the creatures and artifacts that decks are composed of. They have different manas attached to them just like other card types. Most are Basic Lands like Forest, Mountain, and Swamp.",
	},
	{
		id: 23,
		product: "Magic The Gathering Planeswalkers",
		image1: require("../../../../public/magic/planeswalkers/ajani.jpg"),
		image2: require("../../../../public/magic/planeswalkers/jace.jpg"),
		image3: require("../../../../public/magic/planeswalkers/liliana.jpg"),
		image4: require("../../../../public/magic/planeswalkers/nicol.jpg"),
		image5: require("../../../../public/magic/planeswalkers/tezzeret.jpg"),
		price: 11.99,
		desc: "Planeswalkers are powerful card types that can be the key to winning a game. They have different abilites based on a mechanic called loyalty that can be used to unleash their devastating ultimate abilites. Collect cards such as the legendary Jace, Wielder of Mysteries or Tezzeret, Master of Metal.",
	},
	{
		id: 24,
		product: "Magic The Gathering Variety Pack",
		image1: require("../../../../public/magic/creatures/ghalta.jpg"),
		image2: require("../../../../public/magic/enchantments/dream.jpg"),
		image3: require("../../../../public/magic/lands/island.jpg"),
		image4: require("../../../../public/magic/sorceries/blood.jpg"),
		image5: require("../../../../public/magic/planeswalkers/jace.jpg"),
		price: 14.99,
		desc: "The Variety Pack contains a random assortment of cards from the other Magic The Gathering packs. For players looking for a specific card type, it is recommended to purchase packs for that type. The Variety Pack is suited for players that are in need of many kinds of cards to bolster their decks.",
	},
];
